# Generated by Django 4.1.7 on 2023-03-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.AddField(
            model_name='products',
            name='price_12m',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Price per 12 months'),
        ),
        migrations.AddField(
            model_name='products',
            name='price_1m',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Price per month'),
        ),
        migrations.AddField(
            model_name='products',
            name='price_3m',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Price per 3 months'),
        ),
        migrations.AddField(
            model_name='products',
            name='price_6m',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Price per 6 months'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
