# Generated by Django 4.1.7 on 2023-03-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_products_options_remove_products_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available_quantity',
            field=models.IntegerField(blank=True, max_length=8, null=True, verbose_name='Available quantity'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_12m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price per 12 months'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_1m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price per month'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_3m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price per 3 months'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_6m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price per 6 months'),
        ),
    ]
