# Generated by Django 4.1.7 on 2023-03-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_products_available_quantity_alter_products_price_12m_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('available_quantity', models.IntegerField(blank=True, default=-1, null=True, verbose_name='Available quantity')),
                ('price_1m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price per month')),
                ('price_3m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price per 3 months')),
                ('price_6m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price per 6 months')),
                ('price_12m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price per 12 months')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
