# Generated by Django 4.1.7 on 2023-03-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_12m',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_1m',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_3m',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_6m',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='remaining_stock',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
