# Generated by Django 4.1.7 on 2023-03-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_product_available_quantity_remove_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price_12m',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price_1m',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price_3m',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price_6m',
        ),
        migrations.AddField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
