# Generated by Django 4.1.7 on 2023-03-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_subscription_available_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
