# Generated by Django 4.1.7 on 2023-03-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_product_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
    ]
