# Generated by Django 4.2.1 on 2023-05-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_rename_promotionalletter_promotionuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
