# Generated by Django 4.1.7 on 2023-03-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
